### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by marcmayo** [wirecard/magento2-wcs#11]
1) You checkout with a invalid CVV
2) You get back to the Cart with an error message
3) you try to checkout with a invalid CVV again
4) you get back to the cart. But this time the error message is not displaying.

**Comment by jakubpolomsky** [comment]
I will summarize here for all three issues you posted. Of course we will look into them separately. There are multiple projects going on right now, so I would propose we get a look into that, try to reproduce all of the issues and then give you a time scope we might be able to fix these errors. Should you have solutions for these errors feel free to make a pull request to keep the wheels turning.

Regards

**Comment by rinnhofer** [comment]
Errormessages now appear after every failed or canceled payment.
https://github.com/wirecard/magento2-wcs/tree/1.0.6

Cheers
