### ISSUE TITLE
Error Messages translatable

### ISSUE THREAD

**Issue by marcmayo** [wirecard/magento2-wcs#12]
Error messages can't be translated as they get received from the WireCard Server.
I tried to add 
"The financial institution has declined the transaction. Please check the data you have entered.","The financial institution has declined the transaction. Please check the credit card details you have entered"
and it's not working

**Comment by jakubpolomsky** [comment]
Is the string "hard coded" in the source? If not, magento is not able to compile the code properly and translate it. My approach would be to try to translate it in front-end via `$.mage.__('String to translate');`

**Comment by marcmayo** [comment]
no I think the string gets retrieved from the wirecard server. 
@jakubpolomsky I am not a coder so I am not sure where to place this. 
As there is only 1 line for all error codes I am not sure if it would work.
I think these lines get all the errors?

`   case \WirecardCEE_QMore_ReturnFactory::STATE_FAILURE:
                        $returnedData = $paymentInfo->getData();
                        $consumerMessage = "";
                        for ($i = 0; $i < $returnedData['errors']; $i++) {
                            if ($returnedData['errors'] != 1) {
                                $consumerMessage .= $i + 1;
                            }
                            $consumerMessage .= $returnedData['error_' . ($i + 1) . '_consumerMessage'];
                            if ($returnedData['errors'] != 1) {
                                $consumerMessage .= "<br>";
                            }
                        }`

**Comment by jakubpolomsky** [comment]
I see. Therefore I'd suggest waiting for the next update, I might look into that. If this feature will get approved from product management we'll implement a way for our customers to customize error messages.

**Comment by jakubpolomsky** [comment]
After communicating this with our product managment I must inform you, that the plugin will not get any more features. A new plugin for magento 2 is currently under development and it will be released this year already.
