### ISSUE TITLE
German error message shown with special chars

### ISSUE THREAD

**Issue by archonkulis** [wirecard/magento2-wcs#18]
When enterring in-correct card details data for "de" language, user is being redirected back to Magento with following error message -> https://prnt.sc/gjo4zg

Looks like you forgot to decode those characters.

As a hotfix, I added this in the `Back.php` file:

`                            $consumerMessage .= htmlspecialchars_decode($returnedData['error_' . ($i + 1) . '_consumerMessage']);
`

Seems to be working, but you will better know if this is the best place for decoding. I will create a pull request some time later on so you can check that.

Thanks.

**Comment by rinnhofer** [comment]
Hello,
thank you for your input again. We are currently working on the other open issues with magento2-wcs and will fix this issue during this process. 

Cheers

**Comment by rinnhofer** [comment]
Hello,
your changerequest for decoding errormessages is now included in our new release.

Cheers

**Comment by archonkulis** [comment]
@rinnhofer 

I have now version 1.0.4 installed and when I do `composer update wirecard/magento2-wcs`, it updates to only 1.0.5 and not 1.0.6 version.

If I hardcode the version: `composer update wirecard/magento2-wcs:1.0.6`, then it gives me following error:

`./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: wirecard/checkout-client-library[3.3.5, 3.3.4].
    - Can only install one of: wirecard/checkout-client-library[3.3.5, 3.3.4].
    - Can only install one of: wirecard/checkout-client-library[3.3.5, 3.3.4].
    - wirecard/magento2-wcs 1.0.6 requires wirecard/checkout-client-library 3.3.5 -> satisfiable by wirecard/checkout-client-library[3.3.5].
    - Installation request for wirecard/magento2-wcs 1.0.6 -> satisfiable by wirecard/magento2-wcs[1.0.6].
    - Installation request for wirecard/checkout-client-library (locked at 3.3.4) -> satisfiable by wirecard/checkout-client-library[3.3.4].
`

I'm not sure if I'm doing something wrong or is there something not correctly set-up on your side? Can you help me resolve this?

Thanks.
