### ISSUE TITLE
Order paid successfully, but status changes to cancelled

### ISSUE THREAD

**Issue by archonkulis** [wirecard/magento2-wcs#20]
For this one, I don't have any detailed report, but will write all that I know.

When the customer pays with Wirecard, for some reason, sometimes their order got cancelled, although the payment was successful.

This is what we have in debug.log file:

`[2017-09-12 15:09:14] main.DEBUG: Wirecard\CheckoutSeamless\Controller\Checkout\Start::execute:SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '20-98962906-20' for key 'SALES_ORDER_INCREMENT_ID_STORE_ID', query was: INSERT INTO `sales_order` (`state`, `status`, `protect_code`, `shipping_description`, `is_virtual`, `store_id`, `customer_id`, `base_discount_amount`, `base_grand_total`, `base_shipping_amount`, `base_shipping_tax_amount`, `base_subtotal`, `base_tax_amount`, `base_to_global_rate`, `base_to_order_rate`, `discount_amount`, `grand_total`, `shipping_amount`, `shipping_tax_amount`, `store_to_base_rate`, `store_to_order_rate`, `subtotal`, `tax_amount`, `total_qty_ordered`, `customer_is_guest`, `customer_note_notify`, `customer_group_id`, `quote_id`, `base_shipping_discount_amount`, `base_subtotal_incl_tax`, `base_total_due`, `shipping_discount_amount`, `subtotal_incl_tax`, `total_due`, `weight`, `increment_id`, `applied_rule_ids`, `base_currency_code`, `customer_email`, `customer_firstname`, `customer_lastname`, `customer_middlename`, `discount_description`, `global_currency_code`, `order_currency_code`, `remote_ip`, `shipping_method`, `store_currency_code`, `store_name`, `x_forwarded_for`, `total_item_count`, `discount_tax_compensation_amount`, `base_discount_tax_compensation_amount`, `shipping_discount_tax_compensation_amount`, `shipping_incl_tax`, `base_shipping_incl_tax`, `gift_message_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"is_exception":false} []`

And in configs, the Order is created BEFORE Payment, I think this can be the issue. Looking at the code, it creates order in that Start:

`            if ($this->_dataHelper->getConfigData('options/order_creation') == 'before') {
                $this->_orderManagement->submitOrder($this->_cart->getQuote());
            }`

And for some reason, it looks like this function gets run twice, at least by looking at the debug error message it seems so.

Sorry, no further investigations from me, hopefully you can take it from there.

Let me know if you have any questions.

Thanks.

**Comment by rinnhofer** [comment]
Hello,
thank your for your report. When we are finished with the other open issues we are currently working on, we will look into it and give you feedback.

Cheers

**Comment by rinnhofer** [comment]
Hello @archonkulis ,
I tried to reproduce the described behavior but I am afraid that there is to less information to reproduce it.
What payment methods where used? Maybe you can hand in a complete log? Was there a second initialization before this error appeared?

Cheers

**Comment by archonkulis** [comment]
@rinnhofer 

They used Wirecard payment method. Unfortunately, I don't have full log at the moment, since they are removed every day...

Not sure how to proceed with this one. If this will happen again, I will save the debug.log file and will post it here.
