### ISSUE TITLE
Orders are still removed

### ISSUE THREAD

**Issue by archonkulis** [wirecard/magento2-wcs#22]
Hi.

Putting a reference to this issue -> https://github.com/wirecard/magento2-wcs/issues/17

We received a lot more more deleted orders. ( the customers received e-mail but no order can be found in admin / database )

And again we have the same error:
```

    [error_1_errorCode] => 99996
    [error_1_message] => QPAY-Session timed out after 30 minutes without activity.
    [error_1_consumerMessage] => Die QPAY-Benutzersitzung wurde nach 30 min&#252;tiger Inaktivit&#228;t beendet.
    [errors] => 1
    [paymentState] => FAILURE
    [mage_orderId] => 1-68205544
    [mage_quoteId] => 442085
    [mage_orderCreation] => after
    [quoteHash] => 43cee1760941343c9ed5dc0181db6734c05f69ccb682d3a1ff14ed899867cb7a53feef87b8df58181bce72f31eb2afba247f8a37ed8943cdc81820027942a78a
```

For example, here is the order with same error, but it didn't get removed:

```
    [error_1_errorCode] => 99996
    [error_1_message] => QPAY-Session timed out after 30 minutes without activity.
    [error_1_consumerMessage] => QPAY-Session timed out after 30 minutes without activity.
    [errors] => 1
    [paymentState] => FAILURE
    [mage_orderId] => 9-82658869
    [mage_quoteId] => 442141
    [mage_orderCreation] => after
    [quoteHash] => de7e7e18e582dc509b1d1a6bcdbdc7d0e030b76705b90242ef35e011d932428cbb71bc4420d09f4c084bd819879ec5836d92d91a6aecaa77198da74a1b041de2
```

All orders that were removed had this error in common, but not all orders that have this error are removed. So looks like it's somehow connected to this error, but can't seem to understand how.

Can you please describe to me exact steps to reproduce this error? Maybe then we can get a clearer understanding how this could happen?

Also, what's interesting is that not all orders are removed when this error happens - I guess some specific actions need to be done so that order is removed afterward.

Thanks.

**Comment by rinnhofer** [comment]
Hallo,
sorry for the delayed reply. We are currently busy but we will work on this issue as soon as possible.
Just one question for a time: What payment method was used for the deleted orders in those cases so we can test in a specific way when we start.

Thank you for your patience.

Cheers

**Comment by marcmayo** [comment]
Hello,

I am the owner of the shop that's why I reply.

The deleted orders used bank transfer payments.

Regards,


Marc Mayr On Fri, Sep 29, 2017 at 7:29am, rinnhofer < notifications@github.com [notifications@github.com] > wrote:
Hallo,
sorry for the delayed reply. We are currently busy but we will work on this issue as soon as possible.
Just one question for a time: What payment method was used for the deleted orders in those cases so we can test in a specific way when we start.

Thank you for your patience.

Cheers

**Comment by marcmayo** [comment]
Hello,
The deleted orders used bank transfer payment. 
Regards,
Marc (owner of the shop)

**Comment by rinnhofer** [comment]
Hello,
after analysing our source code I found a code snippet which could prevent this behavior. Since we have no possiblity to reproduce deleted bank transfer payments I propose to add a code snippet by yourself and give feedback if your problem got solved by this code snippet.
If this helps we will include it into our next release.

Please insert in vendor/wirecard/magento2-wcs/Model/OrderManagement.php on line 209:
```
if ($orderExists && !$this->isOrderProcessed($order)) {
   $paymentmethod = $order->getPayment()->getMethod();
   if ($paymentmethod == $quote->getPayment()->getMethod()) {
       $this->deleteOrder($order);
   }
}
```
I hope this leads to a solution.

Cheers

**Comment by archonkulis** [comment]
@rinnhofer Sorry, having a hard time understanding where exactly this needs to be inserted. On line 209 there is just closed bracket for a switch statement. A little above that, there is similar code snipper already, but without that payment method comparison. Should I just add that payment method comparison to already existing similar code? Here is the code I see -> https://prnt.sc/gwd71w

Thanks.

**Comment by rinnhofer** [comment]
@archonkulis Yes, you are right it should overwrite the already existing similiar code. Sorry i gave you the wrong line. It is 205.

Cheers

**Comment by archonkulis** [comment]
@rinnhofer Thanks. Will let you know if that worked after some time.

**Comment by archonkulis** [comment]
@rinnhofer Sorry, but orders are still being removed. @marcmayo just reported 2 new orders being removed. There is also no information about these orders in log files...

**Comment by rinnhofer** [comment]
@archonkulis Sorry, I really hope to find a solution for your problem, but my possibilities are restricted here. Maybe you can open a ticket at our support so we can look into your problem with more details. (Access to your testsystem, database entries, configuration, etc) You can reference to the github issue in the support ticket.

Cheers

**Comment by rinnhofer** [comment]
@archonkulis I don't know if you already opened a ticket at our support, but I redirected your problems to our support and you will be contacted soon.

Cheers

**Comment by archonkulis** [comment]
@rinnhofer thanks. @marcmayo already contacted them.
