### ISSUE TITLE
Agreementsassigner is called even when Magento_CheckoutAgreements module is disabled

### ISSUE THREAD

**Issue by archonkulis** [wirecard/magento2-wcs#27]
We have spent a lot of time trying to figure out why logged in users couldn't order with a wirecard and had a js error that stated something like:

` isEnabled called on undefined in vendor/magento/module-checkout-agreements/view/frontend/web/js/model/agreements-assigner.js 21 line`

What I found was that this file was called in:

`vendor/wirecard/magento2-wcs/view/frontend/web/js/action/set-payment-method.js` on 71st line:

by following function: `agreementsAssigner(paymentData);`

And because we had Magento_CheckoutAgreements module disabled ( in `app/etc/config.php` -> `Magento_CheckoutAgreements => 0` ), Magento didn't add the `AgreementsConfigProvider` ( defined in `vendor/magento/module-checkout-agreements/etc/frontend/di.xml` ) to the ConfigProvider list.

After we enabled that extension, there was no js issue anymore.

So, what I think your extension should change is that before calling this function `agreementsAssigner(paymentData);` , it should check if either Magento_CheckoutAgreements is enabled or not or check if `AgreementsConfigProvider` has been loaded.

Let me know if you have any questions.

Thanks.

**Comment by rinnhofer** [comment]
Hello,
thank you for your report. We will implement a solution for this behavior as soon as possible.

Cheers

**Comment by tomazpu** [comment]
We added Checkout Agreements module dependency in composer
