### ISSUE TITLE
Invalid Phone Number

### ISSUE THREAD

**Issue by marcmayo** [wirecard/magento2-wcs#30]
A customer tried to checkout with a phone number with dots in between like "302.182.2819"
He clicked on order with obligation to pay and got redirected to the cart with no error message.
In debug.log we see
I think it should not matter in which format customers enter their phone number
'[2017-10-20 18:30:09] main.DEBUG: Wirecard\CheckoutSeamless\Model\AbstractPayment::initPaymentByCart:Billing phone is invalid.,Shipping phone is invalid. {"is_exception":false} []'
'[2017-10-20 18:30:09] main.DEBUG: Magebit\StarRegistration\Controller\Wirecard\CheckoutSeamless\Checkout\Start::execute:Billing phone is invalid.,Shipping phone is invalid. {"is_exception":false} []'

**Comment by marcmayo** [comment]
Another incorrect format looks like:
   [consumerBillingPhone] => (716)662-1092
    [consumerShippingPhone] => (716)867-3728   (changed numbers)

We also get 
[2017-10-22 19:16:05] main.DEBUG: Wirecard\CheckoutSeamless\Model\AbstractPayment::initPaymentByCart:Billing phone is invalid.,Shipping phone is invalid. {"is_exception":false} []
[2017-10-22 19:16:05] main.DEBUG: Magebit\StarRegistration\Controller\Wirecard\CheckoutSeamless\Checkout\Start::execute:Billing phone is invalid.,Shipping phone is invalid. {"is_exception":false} []


not sure if this is due to the phone numbers are both different or have the brackets around?

**Comment by jakubpolomsky** [comment]
Hello,

thank you for your report. The phone number has no standard format for many countries. There is an issue in our plugin, that the corresponding message is not shown, but I'd suggest changing the phone number format in your shop system to +1 (234) 5678910. I could show you the regex we are comparing the number against if you wish, but this should suffice for now.

Regarding the error-message issue, we will have a look into this in the next two weeks.

Thank you

**Comment by marcmayo** [comment]
@jakubpolomsky where do we set the format? I couldn't find any option for that?

**Comment by jakubpolomsky** [comment]
@marcmayo you just write the correct phone number in your shop or use some kind of validator. For example https://magento.stackexchange.com/questions/155878/validate-mobile-number-in-magento-2 so that your customers are forced to use the desired format.

**Comment by marcmayo** [comment]
@jakubpolomsky  alright I see even tho I think customers should be able to enter it in the desired format as it doesn't really matter? As they could even checkout without a phone number?
Is there a way to deactivate the validation in the wirecard plugin?

**Comment by jakubpolomsky** [comment]
@marcmayo you can disable it in the plugin configuration under the fields `Forward consumer shipping data` and `Forward consumer billing data`.
