### ISSUE TITLE
Successful orders get deleted

### ISSUE THREAD

**Issue by marcmayo** [wirecard/magento2-wcs#36]
@rinnhofer 
I have reproduced https://github.com/wirecard/magento2-wcs/issues/22
The steps you have to take:
1. Checkout
2. Choose Wirecard Credit Card
3. Get forwarded to the 3D MasterCard Secure Tan
4. Navigate back with the Browsers "back" button
5. Choose another payment method and checkout.

-> Order can first be found in the magento Backend, User gets a confirmation E-Mail.
I checked back after around 30 minutes and the order was gone. Not found in the system anymore.

I have made another order and on step 4 I clicked "Cancel" on the secureTan webpage and this order has stayed alive.
Thank you

**Comment by tomazpu** [comment]
Hello @marcmayo

the problem should be fixed in our current release (1.0.11), thank you for your input.

Best regards
