### ISSUE TITLE
Cart not empted after success checkout

### ISSUE THREAD

**Issue by matin73** [wirecard/magento2-wcs#40]
-	Wirecard Seamless Plugin for Magento 2
-	Magento 2.2.3
-	After payment (f.e. Sofortüberweisung) you are redirected to success page of magento shop. But mini-cart is not empted.
-	If you click on button "cart" to check if there is product in cart, but cart is empty

![grafik](https://user-images.githubusercontent.com/3177275/39581856-d8f1deae-4eec-11e8-96cc-2c361ce4b505.png)
![grafik](https://user-images.githubusercontent.com/3177275/39581946-06058d3c-4eed-11e8-9bf6-dc65101e3c14.png)

**Comment by jakubpolomsky** [comment]
Hello

and thank you for your input. The current supported version of magento is 2.2.1 if you could try it with that version first and check again if the plugin behaves the same it could be due to some concurrency issue from an other extension or theme.

In that case you most probably should be able to use this extension with the 2.2.3 version as well.

In every other case, we have planned an update of every extension and this is of course no exception. We'll look into it in parallel with you.

Cheers

**Comment by tomazpu** [comment]
Hello,
the cart not clearing is a known issue from Magento 2. Adding the code below to your success phtml should solve the problem. The file is located at:
module-checkout/view/frontend/templates/success.phtml
Code:
<script>
    require([
        'Magento_Customer/js/customer-data'
        ], function (customerData) {
        var sections = ['cart'];
        customerData.invalidate(sections);
    });
</script>

For more information see: https://github.com/magento/magento2/issues/1461

Cheers

**Comment by matin73** [comment]
I do not think this is Magento bug, because all other payment methods work correct. Only Wirecard payments are not clearing cart. So this must be a bug of you module.

 

Martin

 

***********************************

Wir machen Urlaub! Vom 11. Bis 16. Juni 2018!

***********************************

Weymayer GmbH

Martin Weymayer

Grillparz 9, 4554 Oberschlierbach

Tel.: +43 664 9231847

Internet: www.weymayer.at <http://www.weymayer.at/>  

UID Nr.: ATU68228269

FN: 402285x, Landesgericht Steyr

***********************************

 

Von: tomazpu [mailto:notifications@github.com] 
Gesendet: Dienstag, 15. Mai 2018 08:08
An: wirecard/magento2-wcs
Cc: matin73; Author
Betreff: Re: [wirecard/magento2-wcs] Cart not empted after success checkout (#40)

 

Hello,
the cart not clearing is a known issue from Magento 2. Adding the code below to your success phtml should solve the problem. The file is located at:
module-checkout/view/frontend/templates/success.phtml
Code:

<script> require([ 'Magento_Customer/js/customer-data' ], function (customerData) { var sections = ['cart']; customerData.invalidate(sections); }); </script> 

For more information see: magento/magento2#1461 <https://github.com/magento/magento2/issues/1461> 

Cheers

**Comment by tomazpu** [comment]
Hello, 
thank you for your input, the issue is with the new release 1.0.13 fixed.

Cheers
