### ISSUE TITLE
Agreements not assigned to payment when not logged in

### ISSUE THREAD

**Issue by nussjustin-hmmh** [wirecard/magento2-wcs#41]
When making an order as a guest the Wirecard Javascript does not assign the agreements to the payment data, which prevents the user from getting past the payment method step and to the payment.

Relevant Code:

https://github.com/wirecard/magento2-wcs/blob/dc1223de28ced22fb418bb3fc6d0e6674c6546e0/view/frontend/web/js/action/set-payment-method.js#L59-L77

**Comment by tomazpu** [comment]
Hello, 
thank you for your input. The issue is solved with the new release:
https://github.com/wirecard/magento2-wcs/releases/tag/1.0.12

Cheers
