### ISSUE TITLE
Transactiondetails in order view

### ISSUE THREAD

**Issue by mvenghaus** [wirecard/magento2-wcs#47]
### Versions

**Magento 2 version:** 2.2.5 
**PHP version:** 7.1.11
**Module version:** 1.0.13

### Issue

In the Magento 1 version of your module we see additional transaction information like reference number or contractnumber on the order view.
This module shows no information. Is there an option to activate this or is it missing in this module?

Regards
Marcus

**Comment by tomazpu** [comment]
Hello Marcus, 

in the Order view under Transactions and then if you click on the specific transaction you can see all the available data. See the screenshot bellow. I hope this answers your question. Note that this is only a sample transaction from ideal.

![2018-09-04_08h21_17](https://user-images.githubusercontent.com/32056440/45013613-07b9f380-b01c-11e8-9c0a-0e6ce59e1691.jpg)


Best Regards
Tomaz
