### ISSUE TITLE
UNINSTALL MODULE ERROR

### ISSUE THREAD

**Issue by corpsysgit** [wirecard/magento2-wcs#51]
### Prerequisites

- [ X] I have my [server set up correctly](https://guides.wirecard.at/shop_plugins:wcs:magento2:installation).
- [X ] I am using a [supported version of Magento 2](https://guides.wirecard.at/shop_plugins:wcs:magento2:start).

### Versions

**Magento 2 version:** ...2.3
**PHP version:** ...7

### Issue

UNINSTALL MODULE ERROR

**Problem description:**

1 exception(s):
Exception #0 (Magento\Framework\Exception\FileSystemException): The contents from the "/home/melbourne/public_html/vendor/wirecard/magento2-wcs/etc/module.xml" file can't be read. Warning!file_get_contents(/home/melbourne/public_html/vendor/wirecard/magento2-wcs/etc/module.xml): failed to open stream: No such file or directory

Exception #0 (Magento\Framework\Exception\FileSystemException): The contents from the "/home/melbourne/public_html/vendor/wirecard/magento2-wcs/etc/module.xml" file can't be read. Warning!file_get_contents(/home/melbourne/public_html/vendor/wirecard/magento2-wcs/etc/module.xml): failed to open stream: No such file or directory
#0 /home/melbourne/public_html/vendor/magento/framework/Module/ModuleList/Loader.php(120): Magento\Framework\Filesystem\Driver\File->fileGetContents('/home/melbourne...')
#1 /home/melbourne/public_html/vendor/magento/framework/Module/ModuleList/Loader.php(81): Magento\Framework\Module\ModuleList\Loader->getModuleConfigs()
#2 /home/melbourne/public_html/vendor/magento/framework/Module/ModuleList.php(72): Magento\Framework\Module\ModuleList\Loader->load()
#3 /home/melbourne/public_html/vendor/magento/framework/Module/ModuleList.php(92): Magento\Framework\Module\ModuleList->getAll()
#4 /home/melbourne/public_html/vendor/magento/framework/Module/DbVersionInfo.php(144): Magento\Framework\Module\ModuleList->getOne('Magento_Store')
#5 /home/melbourne/public_html/vendor/magento/framework/Module/DbVersionInfo.php(59): Magento\Framework\Module\DbVersionInfo->isModuleVersionEqual('Magento_Store', false)
#6 /home/melbourne/public_html/vendor/magento/framework/Module/DbVersionInfo.php(103): Magento\Framework\Module\DbVersionInfo->isSchemaUpToDate('Magento_Store')
#7 /home/melbourne/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(119): Magento\Framework\Module\DbVersionInfo->getDbVersionErrors()
#8 /home/melbourne/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(53): Magento\Framework\Module\Plugin\DbStatusValidator->getGroupedDbVersionErrors()
#9 /home/melbourne/public_html/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Framework\Module\Plugin\DbStatusValidator->beforeDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Magento\Framework\App\Request\Http))
#10 /home/melbourne/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /home/melbourne/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /home/melbourne/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /home/melbourne/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#14 /home/melbourne/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /home/melbourne/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#16 /home/melbourne/public_html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))

**Steps to reproduce:**

bin/magento module:uninstall Wirecard_CheckoutSeamless
composer remove wirecard/magento2-wcs

...

**Comment by serucee** [comment]
Hello @corpsysgit ,

sorry for the late response. We will look into the described issue and inform you as soon as possible.

Kind regards,
Wirecard Shop Systems Team

**Comment by miha1** [comment]
Hello @corpsysgit ,
We did try to reproduce your behavior, but we didn't have any problems with uninstallation of the plugin.
Please check your r/w permission.
